import { Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: {
    template: "%s | Academia",
    default: "Academia | Home",
  },
  description: "Generated by create next app",

  keywords: ["Academia"],
  // openGraph: {
  //   images: "/opengraph-image.png",
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
